setwd('data/')
filename<-list.files(pattern="*Genus*")
dg<-lapply(filename, function(x)read.csv(x))
names(dg)<-sub('DifferentialGenus_','',sub('.csv','',filename))
tseae<-read.csv("tsea_ext.csv",row.names = 1)
write.csv(tseae[tseae$member%in%intersect(subset(dg$Cgas,pvalue<0.05&(log2FoldChange>1|log2FoldChange< -1))$Genus,tseae$member),],file="cgas_environment.csv")
write.csv(tseae[tseae$member%in%intersect(subset(dg$DSS,pvalue<0.05&(log2FoldChange>1|log2FoldChange< -1))$Genus,tseae$member),],file="DSS_environment.csv")
library(richR)
dsse<-enrich(subset(dg$DSS,pvalue<0.05&(log2FoldChange>1|log2FoldChange< -1))$Genus,annot = tseae)
cgase<-enrich(subset(dg$Cgas,pvalue<0.05&(log2FoldChange>1|log2FoldChange< -1))$Genus,annot = tseae)
com<-compareResult(list(DSS=dsse,Cgas=cgase))
comparedot(com,short=T,usePadj=F)